import type { Metadata } from "next";
import "./globals.css";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { JimmySans, Satoshi, Ranade } from "@/fonts";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Khedma market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`scroll-smooth antialiased ${GeistSans.className} ${GeistMono.variable} ${JimmySans.variable} ${Satoshi.variable} ${Ranade.variable}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
